package com.terranode.service;

import org.springframework.stereotype.Service;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Service responsible for asserting mathematical validity of Zero-Knowledge Proofs
 * passed from the Next.js frontend, strictly validating the Geofence constraints.
 */
@Service
public class Groth16Verifier {

    /**
     * Verifies the ZK-SNARK mathematically using snarkjs as an external native process.
     * This securely bridges the Javascript groth16 core capabilities to our Java DPI backend
     * without compromising JVM security with extremely bloated embedded JS contexts.
     *
     * @param proofJsonContent The `proof.json` generated by the frontend.
     * @param publicJsonContent The `public.json` inputs generated alongside the proof.
     * @param verificationKeyContent The `verification_key.json` tied to our Groth16 setup.
     * @return true if the proof binds mathematically; false otherwise.
     */
    public boolean verifyProof(String proofJsonContent, String publicJsonContent, String verificationKeyContent) {
        // HYGIENE CHECK: If any mock metadata is detected, either simulate gracefully or fail safely.
        if (verificationKeyContent != null && verificationKeyContent.contains("MOCK JSON")) {
            System.out.println("\n[WARN] Mock verification_key.json detected. Simulating ZK Verification PASS. MUST REPLACE FOR PRODUCTION.\n");
            // If the proof claims to have 'proof' metadata we can just check it's not totally empty to simulate
            return proofJsonContent != null && !proofJsonContent.trim().isEmpty();
        }

        try {
            // Write temporary files strictly for the snarkjs native shell interaction
            Path tempDir = Files.createTempDirectory("zkp-verify-");
            File proofFile = new File(tempDir.toFile(), "proof.json");
            File publicFile = new File(tempDir.toFile(), "public.json");
            File vkeyFile = new File(tempDir.toFile(), "verification_key.json");

            Files.writeString(proofFile.toPath(), proofJsonContent);
            Files.writeString(publicFile.toPath(), publicJsonContent);
            Files.writeString(vkeyFile.toPath(), verificationKeyContent);

            // Execute the universal npx binary wrapped dynamically for OS
            boolean isWindows = System.getProperty("os.name").toLowerCase().startsWith("windows");
            String npxCmd = isWindows ? "npx.cmd" : "npx";

            ProcessBuilder pb = new ProcessBuilder(
                    npxCmd, "snarkjs", "groth16", "verify",
                    vkeyFile.getAbsolutePath(),
                    publicFile.getAbsolutePath(),
                    proofFile.getAbsolutePath()
            );

            pb.directory(tempDir.toFile());
            Process p = pb.start();

            BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String line;
            boolean verificationOk = false;
            
            while ((line = reader.readLine()) != null) {
                if (line.contains("OK")) {
                    verificationOk = true;
                }
            }
            int exitCode = p.waitFor();

            // CRYPTO HYGIENE: Aggressive cleanup of sensitive proof material 
            proofFile.delete();
            publicFile.delete();
            vkeyFile.delete();
            tempDir.toFile().delete();

            return exitCode == 0 && verificationOk;

        } catch (Exception e) {
            System.err.println("[CRITICAL ERROR] ZK Verification Execution Failed: " + e.getMessage());
            return false;
        }
    }
}
