package com.terranode.service;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.util.HexFormat;

/**
 * Service responsible for asserting mathematical validity of Zero-Knowledge Proofs
 * passed from the Next.js frontend, strictly validating the Geofence constraints.
 */
@Service
public class Groth16Verifier {

    private static final Logger log = LoggerFactory.getLogger(Groth16Verifier.class);

    /**
     * On application startup, reads verification_key.json from the classpath and logs:
     *  1. The first 80 characters (to confirm it's the real key, not a stub)
     *  2. A SHA-256 fingerprint (so you can cross-check against the file on disk)
     *
     * If the log shows: "MOCK_ZKEY_PLACEHOLDER" or short plain text → the old stub is
     * still in the JAR. If it shows: {"protocol":"groth16","curve":"bn128"... → it's real.
     */
    @PostConstruct
    public void logVerificationKeyFingerprint() {
        try (InputStream is = new ClassPathResource("verification_key.json").getInputStream()) {
            byte[] keyBytes = is.readAllBytes();
            String preview = new String(keyBytes, StandardCharsets.UTF_8)
                    .substring(0, Math.min(80, keyBytes.length))
                    .replaceAll("\\s+", " ")
                    .trim();

            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(keyBytes);
            String fingerprint = HexFormat.of().formatHex(hash);

            log.info("\n╔══════════════════════════════════════════════════════════╗");
            log.info("║  [VKEY FINGERPRINT] Classpath: verification_key.json     ║");
            log.info("║  Size   : {} bytes", keyBytes.length);
            log.info("║  Preview: {}...", preview);
            log.info("║  SHA-256: {}", fingerprint);
            log.info("╚══════════════════════════════════════════════════════════╝\n");

            if (preview.contains("MOCK") || preview.contains("placeholder") || keyBytes.length < 500) {
                log.warn("[VKEY WARNING] verification_key.json is a stub ({} bytes). " +
                         "Groth16Verifier will auto-accept proofs in DEMO MOCK MODE. " +
                         "Re-run `node compile.js` in /zkp and rebuild the backend to use real verification.",
                         keyBytes.length);
            }

        } catch (Exception e) {
            log.error("[VKEY ERROR] Could not read verification_key.json from classpath: {}", e.getMessage());
        }
    }

    /**
     * Returns true if the classpath verification_key.json is a stub/placeholder.
     * In that case, any structurally non-null proof is accepted for demo continuity.
     */
    private boolean isVkeyStub() {
        try (InputStream is = new ClassPathResource("verification_key.json").getInputStream()) {
            byte[] keyBytes = is.readAllBytes();
            String content = new String(keyBytes, StandardCharsets.UTF_8);
            return keyBytes.length < 500 || content.contains("MOCK") || content.contains("placeholder");
        } catch (Exception e) {
            return true; // If we can't read it, treat as stub → degrade gracefully
        }
    }

    /**
     * Verifies the ZK-SNARK mathematically using snarkjs as an external native process.
     *
     * @param proofJsonContent  The proof JSON string generated by the frontend.
     * @param publicJsonContent The publicSignals JSON array string.
     * @return true if the proof binds mathematically; false otherwise.
     */
    public boolean verifyProof(String proofJsonContent, String publicJsonContent) {
        // ── DEMO MOCK MODE ────────────────────────────────────────────────────────────
        // If the classpath verification_key.json is still a stub (< 500 bytes or contains
        // "MOCK"/"placeholder"), skip the real snarkjs process and auto-accept any
        // structurally valid (non-empty) proof. This keeps the full pipeline running
        // until real ZKP artifacts are compiled and the image is rebuilt.
        if (isVkeyStub()) {
            boolean hasProof = proofJsonContent != null && !proofJsonContent.isBlank();
            log.warn("[ZKP MOCK MODE] Stub vkey detected — auto-{} proof without snarkjs execution.",
                     hasProof ? "ACCEPTING" : "REJECTING (empty proof)");
            return hasProof;
        }

        Path tempDir = null;
        try {
            tempDir = Files.createTempDirectory("zkp-verify-");

            File proofFile  = new File(tempDir.toFile(), "proof.json");
            File publicFile = new File(tempDir.toFile(), "public.json");
            File vkeyFile   = new File(tempDir.toFile(), "verification_key.json");

            // ── 1. Write proof & public signals ──────────────────────────────
            Files.writeString(proofFile.toPath(), proofJsonContent);
            Files.writeString(publicFile.toPath(), publicJsonContent);

            // ── 2. Stream real vkey from classpath (always fresh per call) ───
            try (InputStream is = new ClassPathResource("verification_key.json").getInputStream()) {
                Files.copy(is, vkeyFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            }

            // Log size of vkey just copied — quick sanity check in the logs
            log.info("[ZKP] Temp vkey written: {} bytes | proof: {} bytes | public: {} bytes",
                    vkeyFile.length(), proofFile.length(), publicFile.length());

            // ── 3. Resolve snarkjs command ───────────────────────────────────
            boolean isWindows = System.getProperty("os.name").toLowerCase().startsWith("windows");
            String snarkjsCmd = isWindows ? "snarkjs.cmd" : "snarkjs";

            ProcessBuilder pb = new ProcessBuilder(
                    snarkjsCmd, "groth16", "verify",
                    vkeyFile.getAbsolutePath(),
                    publicFile.getAbsolutePath(),
                    proofFile.getAbsolutePath()
            );
            pb.directory(tempDir.toFile());

            Process p = pb.start();

            // ── 4. Read stdout for OK signal ─────────────────────────────────
            StringBuilder stdoutLog = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    stdoutLog.append(line).append("\n");
                }
            }

            int exitCode = p.waitFor();
            boolean verificationOk = stdoutLog.toString().contains("OK");

            // ── 5. Capture stderr on failure — full diagnostics ──────────────
            if (exitCode != 0 || !verificationOk) {
                StringBuilder stderrLog = new StringBuilder();
                try (BufferedReader errReader = new BufferedReader(new InputStreamReader(p.getErrorStream()))) {
                    String errLine;
                    while ((errLine = errReader.readLine()) != null) {
                        stderrLog.append(errLine).append("\n");
                    }
                }
                log.error("\n[ZKP FAIL] snarkjs exited {} | stdout:\n{}\nstderr:\n{}",
                        exitCode, stdoutLog, stderrLog);
            } else {
                log.info("[ZKP] ✅ Groth16 verification PASSED | exitCode={}", exitCode);
            }

            return exitCode == 0 && verificationOk;

        } catch (Exception e) {
            log.error("[ZKP CRITICAL] Verification execution failed: ", e);
            return false;

        } finally {
            // ── Crypto hygiene: wipe entire temp dir regardless of outcome ───
            if (tempDir != null) {
                try {
                    File[] files = tempDir.toFile().listFiles();
                    if (files != null) {
                        for (File f : files) f.delete();
                    }
                    tempDir.toFile().delete();
                } catch (Exception ignored) {}
            }
        }
    }
}
